music = {
    # --- Existing Songs ---
    "naina" : "https://youtu.be/9IzaWBsUhCU?si=JIED7W7wOsnZ8LL6" ,
    "nusta paisa" : "https://youtu.be/s1TBzhmt1vU?si=-0gbo-hoVXwDCY34" ,
    "nanchaku" : "https://youtu.be/VjJtH7xM8G4?si=GUne73m1asL4G5S2" ,
    "shape of you" : "https://youtu.be/liTfD88dbCo?si=1wQVa7afIdBwKahb" ,
    "dubai company" : "https://youtu.be/Pr1OdTzZDpQ?si=yhUQgZRWX0f0fBfc",
    "rx 100" : "https://youtu.be/cfYCUKQtmp0?si=OJ8EWKrTJr0NCcgD" ,
    "bargad" : "https://youtu.be/BBM57gr9fFU?si=h6klhGLa1_pwyEJJ" ,
    "dil nu " : "https://youtu.be/p2EdDiiVHh4?si=oHFsDOP4psZLHhF1" ,
    "be inteehan" : "https://youtu.be/XSdupl2VNBM?si=QdWD0j3hqvH1XGkt",

    # --- Top 50 Coke Studio Pakistan Songs ---
    "pasoori" : "https://youtu.be/smf-c5nFkK4" ,
    "tajdar e haram" : "https://youtu.be/M9K7VIi93Cg" ,
    "afreen afreen" : "https://youtu.be/K1Y1aI0oJio" ,
    "tu kuja man kuja" : "https://youtu.be/ZQMn5wIoAno" ,
    "tera woh pyar" : "https://youtu.be/XgUj_aM9zIA" ,
    "wohi khuda hai" : "https://youtu.be/H7yP-1d0BIA" ,
    "sammi meri waar" : "https://youtu.be/g_Qx_C6L5bM" ,
    "asma ul husna" : "https://youtu.be/d9-x8R0k03Q" ,
    "man aamadeh am" : "https://youtu.be/f_lD43a-U9E" ,
    "kana yaari" : "https://youtu.be/t5JmS7I-F9o" ,
    "tu jhoom" : "https://youtu.be/0k5I3_4v5qI" ,
    "alif allah jugni" : "https://youtu.be/p4vW7c-s5I4" ,
    "lagi bina" : "https://youtu.be/b4p1F-t4aYc" ,
    "rockstar" : "https://youtu.be/ZwINALbVF7w" ,
    "harkalay" : "https://youtu.be/4QgqGxPMI6Y" ,
    "charkha naulakha" : "https://youtu.be/o0_L9v4uLGY" ,
    "piya piya calling" : "https://youtu.be/mfblDS1129I" ,
    "aayi aayi" : "https://youtu.be/sW1E0P07p_A" ,
    "miyan ki malhaar" : "https://youtu.be/u7R4kdCi1zY" ,
    "peechay hutt" : "https://youtu.be/3ePx7BXWP-g" ,
    "latthay di chaadar" : "https://youtu.be/iqEFGBilHxc" ,
    "baazi" : "https://youtu.be/IwOF93jRFYg" ,
    "malang" : "https://youtu.be/F13JkFsjbcE" ,
    "sayonee" : "https://youtu.be/j9GzTysXyT4" ,
    "roye roye" : "https://youtu.be/oYaJC4yUQMo" ,
    "dhola" : "https://youtu.be/IILNF_DORIA" ,
    "baliye laung gawacha" : "https://youtu.be/SlfP4tQDkH4" ,
    "aatish" : "https://youtu.be/IfDInEDeN3o" ,
    "heeray" : "https://youtu.be/zxFmCgXPh6I" ,
    "garaj baras" : "https://youtu.be/jE-Krlqi4fk" ,
    "chaap tilak" : "https://youtu.be/8p10IiPW1rQ" ,
    "aaqa" : "https://youtu.be/CTRC1nTbr3o" ,
    "ghoom charakhra" : "https://youtu.be/NvMd3qI-0PU" ,
    "dost" : "https://youtu.be/xQfEpuI7APs" ,
    "rangreza" : "https://youtu.be/nHIJ7R9Yggg" ,
    "sadaa" : "https://youtu.be/lxGM3jfLvOY" ,
    "khaki banda" : "https://youtu.be/bDK71QdEW14" ,
    "chal raha hoon" : "https://youtu.be/q_UwzlIJQ9E" ,
    "ballay ballay" : "https://youtu.be/eO_zPGJbvT4" ,
    "sab jag soye" : "https://youtu.be/dB5PZBIipkQ" ,
    "har funn maula" : "https://youtu.be/qM6gZ0KhEsk" ,
    "baanware" : "https://youtu.be/J0YVm5K1gZo" ,
    "umran langiyaan" : "https://youtu.be/x5oaT-vGIVI" ,
    "ramooz e ishq" : "https://youtu.be/U3JKjQcZ5cE" ,
    "mein sufi hoon" : "https://youtu.be/s_B_OHGc8GQ" ,
    "ishq aap bhi awalla" : "https://youtu.be/bGlwSGXn_r0" ,
    "ae dil" : "https://youtu.be/tXXp2VbfHDQ" ,
    "taaray" : "https://youtu.be/IVjU7HKfY-o" ,
    "phir milenge" : "https://youtu.be/fksMqOg3jRU" ,
    "mehdi laga ke rakhna" : "https://youtu.be/5dCfLf3Fkh0" ,

}

# git status
# git add  .
# git commit -m "translator module "
# git push origin main                  
